version: "3.8"
services:
  #Laravel Service
  ts_web:
    container_name: ts_web
    restart: always
    tty: true
    working_dir: /var/www/html/thescore
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html/thescore
    depends_on:
      - ts_db
    links:
      - ts_db
    networks:
      - ts_network

  #DB Service
  ts_db:
    image: mariadb:latest
    container_name: ts_db
    restart: always
    working_dir: /etc/mysql
    tty: true
    environment:
      MYSQL_DATABASE: the_score
      MYSQL_USER: lee
      MYSQL_ROOT_PASSWORD: dennis
      MYSQL_PASSWORD: dennis
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - ts_network

  #Nginx Service
  ts_server:
    image: nginx:alpine
    container_name: ts_server
    restart: always
    tty: true
    ports:
      - 8100:8080
    volumes:
      - .:/var/www/html/thescore
      - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    depends_on:
      - ts_web
    networks:
      - ts_network

#Docker Networks
networks:
  ts_network:
    driver: bridge
volumes:
  dbdata:
    driver: local
